// <auto-generated />
using System;
using MDC.Server.Data.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MDC.Server.Data.Migrations
{
    [DbContext(typeof(MDCDbContext))]
    [Migration("20231220125459_RegionModifyMigrations")]
    partial class RegionModifyMigrations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MDC.Server.Domain.Entities.Communities.Community", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Banner")
                        .HasColumnType("text");

                    b.Property<string>("Bio")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Logo")
                        .HasColumnType("text");

                    b.Property<long?>("ParentId")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Communities");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Banner = "tech_banner.jpg",
                            Bio = "Explore the latest in tech trends.",
                            CreatedAt = new DateTime(2023, 12, 20, 12, 54, 58, 563, DateTimeKind.Utc).AddTicks(3053),
                            Description = "A community for technology enthusiasts.",
                            Logo = "tech_logo.png",
                            Title = "Tech Enthusiasts",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2L,
                            Banner = "outdoor_banner.jpg",
                            Bio = "Connect with nature and fellow adventurers.",
                            CreatedAt = new DateTime(2023, 12, 20, 12, 54, 58, 563, DateTimeKind.Utc).AddTicks(3055),
                            Description = "For those who love outdoor activities.",
                            Logo = "outdoor_logo.png",
                            Title = "Outdoor Adventures",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3L,
                            Banner = "books_banner.jpg",
                            Bio = "Discuss your favorite books and discover new ones.",
                            CreatedAt = new DateTime(2023, 12, 20, 12, 54, 58, 563, DateTimeKind.Utc).AddTicks(3057),
                            Description = "A community for bookworms and literature enthusiasts.",
                            Logo = "books_logo.png",
                            Title = "Book Lovers Club",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4L,
                            Banner = "fitness_banner.jpg",
                            Bio = "Share workout tips and stay motivated.",
                            CreatedAt = new DateTime(2023, 12, 20, 12, 54, 58, 563, DateTimeKind.Utc).AddTicks(3058),
                            Description = "For fitness enthusiasts and health-conscious individuals.",
                            Logo = "fitness_logo.png",
                            Title = "Fitness Fanatics",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5L,
                            Banner = "art_banner.jpg",
                            Bio = "Connect with fellow artists and creators.",
                            CreatedAt = new DateTime(2023, 12, 20, 12, 54, 58, 563, DateTimeKind.Utc).AddTicks(3059),
                            Description = "Explore and share your artistic side.",
                            Logo = "art_logo.png",
                            Title = "Art and Creativity",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("MDC.Server.Domain.Entities.Communities.CommunityRole", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("CommunityRoles");

                    b.HasData(
                        new
                        {
                            Id = (short)1,
                            CreatedAt = new DateTime(2023, 12, 20, 12, 54, 58, 563, DateTimeKind.Utc).AddTicks(3146),
                            Description = "Community administrator role.",
                            Name = "Administrator",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = (short)2,
                            CreatedAt = new DateTime(2023, 12, 20, 12, 54, 58, 563, DateTimeKind.Utc).AddTicks(3147),
                            Description = "Standard community member role.",
                            Name = "Member",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = (short)3,
                            CreatedAt = new DateTime(2023, 12, 20, 12, 54, 58, 563, DateTimeKind.Utc).AddTicks(3148),
                            Description = "Community moderator role.",
                            Name = "Moderator",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = (short)4,
                            CreatedAt = new DateTime(2023, 12, 20, 12, 54, 58, 563, DateTimeKind.Utc).AddTicks(3149),
                            Description = "Guest role for limited access.",
                            Name = "Guest",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = (short)5,
                            CreatedAt = new DateTime(2023, 12, 20, 12, 54, 58, 563, DateTimeKind.Utc).AddTicks(3150),
                            Description = "Community content editor role.",
                            Name = "Editor",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("MDC.Server.Domain.Entities.Communities.UserCommunity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CommunityId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<short>("RoleId")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CommunityId");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("UserCommunities");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CommunityId = 1L,
                            CreatedAt = new DateTime(2023, 12, 20, 12, 54, 58, 563, DateTimeKind.Utc).AddTicks(3232),
                            RoleId = (short)1,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = "1"
                        },
                        new
                        {
                            Id = 2L,
                            CommunityId = 2L,
                            CreatedAt = new DateTime(2023, 12, 20, 12, 54, 58, 563, DateTimeKind.Utc).AddTicks(3233),
                            RoleId = (short)2,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = "2"
                        },
                        new
                        {
                            Id = 3L,
                            CommunityId = 3L,
                            CreatedAt = new DateTime(2023, 12, 20, 12, 54, 58, 563, DateTimeKind.Utc).AddTicks(3234),
                            RoleId = (short)1,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = "3"
                        },
                        new
                        {
                            Id = 4L,
                            CommunityId = 4L,
                            CreatedAt = new DateTime(2023, 12, 20, 12, 54, 58, 563, DateTimeKind.Utc).AddTicks(3236),
                            RoleId = (short)3,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = "4"
                        },
                        new
                        {
                            Id = 5L,
                            CommunityId = 5L,
                            CreatedAt = new DateTime(2023, 12, 20, 12, 54, 58, 563, DateTimeKind.Utc).AddTicks(3237),
                            RoleId = (short)2,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = "5"
                        });
                });

            modelBuilder.Entity("MDC.Server.Domain.Entities.Events.Event", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime?>("EndAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Format")
                        .HasColumnType("integer");

                    b.Property<string>("LiveStreamUrl")
                        .HasColumnType("text");

                    b.Property<long?>("LocationId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("StartAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedAt = new DateTime(2023, 12, 20, 12, 54, 58, 563, DateTimeKind.Utc).AddTicks(2656),
                            Description = "Explore the latest in technology and innovation.",
                            EndAt = new DateTime(2023, 12, 20, 12, 54, 58, 563, DateTimeKind.Utc).AddTicks(2655),
                            Format = 0,
                            LiveStreamUrl = "https://livestream.example.com/tech-conference",
                            LocationId = 1L,
                            StartAt = new DateTime(2024, 1, 20, 12, 54, 58, 563, DateTimeKind.Utc).AddTicks(2645),
                            Status = 0,
                            Title = "Tech Conference 2023",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2L,
                            CreatedAt = new DateTime(2023, 12, 20, 12, 54, 58, 563, DateTimeKind.Utc).AddTicks(2660),
                            Description = "Join us for a fitness extravaganza.",
                            EndAt = new DateTime(2023, 12, 20, 12, 54, 58, 563, DateTimeKind.Utc).AddTicks(2659),
                            Format = 3,
                            LocationId = 2L,
                            StartAt = new DateTime(2023, 12, 20, 12, 54, 58, 563, DateTimeKind.Utc).AddTicks(2659),
                            Status = 0,
                            Title = "Fitness Expo",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3L,
                            CreatedAt = new DateTime(2023, 12, 20, 12, 54, 58, 563, DateTimeKind.Utc).AddTicks(2662),
                            Description = "Discuss your favorite books with fellow bookworms.",
                            EndAt = new DateTime(2023, 12, 20, 12, 54, 58, 563, DateTimeKind.Utc).AddTicks(2662),
                            Format = 1,
                            LocationId = 3L,
                            StartAt = new DateTime(2023, 12, 20, 12, 54, 58, 563, DateTimeKind.Utc).AddTicks(2661),
                            Status = 0,
                            Title = "Book Club Meeting",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4L,
                            CreatedAt = new DateTime(2023, 12, 20, 12, 54, 58, 563, DateTimeKind.Utc).AddTicks(2664),
                            Description = "Discover and appreciate local artistic talent.",
                            EndAt = new DateTime(2023, 12, 20, 12, 54, 58, 563, DateTimeKind.Utc).AddTicks(2664),
                            Format = 0,
                            LocationId = 4L,
                            StartAt = new DateTime(2023, 12, 20, 12, 54, 58, 563, DateTimeKind.Utc).AddTicks(2663),
                            Status = 0,
                            Title = "Art Exhibition",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5L,
                            CreatedAt = new DateTime(2023, 12, 20, 12, 54, 58, 563, DateTimeKind.Utc).AddTicks(2667),
                            Description = "Join hands for a cleaner and greener community.",
                            EndAt = new DateTime(2023, 12, 20, 12, 54, 58, 563, DateTimeKind.Utc).AddTicks(2666),
                            Format = 0,
                            LocationId = 5L,
                            StartAt = new DateTime(2023, 12, 20, 12, 54, 58, 563, DateTimeKind.Utc).AddTicks(2666),
                            Status = 4,
                            Title = "Community Cleanup",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("MDC.Server.Domain.Entities.Events.EventAsset", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("EventId")
                        .HasColumnType("bigint");

                    b.Property<string>("Image")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.ToTable("EventAssets");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedAt = new DateTime(2023, 12, 20, 12, 54, 58, 563, DateTimeKind.Utc).AddTicks(2717),
                            EventId = 1L,
                            Image = "event-asset-image-1.jpg",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2L,
                            CreatedAt = new DateTime(2023, 12, 20, 12, 54, 58, 563, DateTimeKind.Utc).AddTicks(2718),
                            EventId = 2L,
                            Image = "event-asset-image-2.jpg",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3L,
                            CreatedAt = new DateTime(2023, 12, 20, 12, 54, 58, 563, DateTimeKind.Utc).AddTicks(2719),
                            EventId = 3L,
                            Image = "event-asset-image-3.jpg",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4L,
                            CreatedAt = new DateTime(2023, 12, 20, 12, 54, 58, 563, DateTimeKind.Utc).AddTicks(2720),
                            EventId = 4L,
                            Image = "event-asset-image-4.jpg",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5L,
                            CreatedAt = new DateTime(2023, 12, 20, 12, 54, 58, 563, DateTimeKind.Utc).AddTicks(2721),
                            EventId = 5L,
                            Image = "event-asset-image-5.jpg",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("MDC.Server.Domain.Entities.Events.EventRole", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("EventRoles");

                    b.HasData(
                        new
                        {
                            Id = (short)1,
                            CreatedAt = new DateTime(2023, 12, 20, 12, 54, 58, 563, DateTimeKind.Utc).AddTicks(2688),
                            Description = "Responsible for planning and managing the event.",
                            Name = "Organizer",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = (short)2,
                            CreatedAt = new DateTime(2023, 12, 20, 12, 54, 58, 563, DateTimeKind.Utc).AddTicks(2689),
                            Description = "Presenting talks or sessions during the event.",
                            Name = "Speaker",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = (short)3,
                            CreatedAt = new DateTime(2023, 12, 20, 12, 54, 58, 563, DateTimeKind.Utc).AddTicks(2690),
                            Description = "Attending the event without a specific role.",
                            Name = "Participant",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = (short)4,
                            CreatedAt = new DateTime(2023, 12, 20, 12, 54, 58, 563, DateTimeKind.Utc).AddTicks(2690),
                            Description = "Assisting with various tasks during the event.",
                            Name = "Volunteer",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = (short)5,
                            CreatedAt = new DateTime(2023, 12, 20, 12, 54, 58, 563, DateTimeKind.Utc).AddTicks(2691),
                            Description = "Supporting the event financially or with resources.",
                            Name = "Sponsor",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("MDC.Server.Domain.Entities.Events.EventSession", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime?>("EndAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("EventId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("SpeakerId")
                        .HasColumnType("text");

                    b.Property<DateTime?>("StartAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("SpeakerId");

                    b.ToTable("EventSessions");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedAt = new DateTime(2023, 12, 20, 12, 54, 58, 563, DateTimeKind.Utc).AddTicks(2750),
                            Description = "An inspiring keynote to kick off the event.",
                            EndAt = new DateTime(2024, 1, 21, 13, 54, 58, 563, DateTimeKind.Utc).AddTicks(2748),
                            EventId = 1L,
                            Name = "Keynote Address",
                            SpeakerId = "1",
                            StartAt = new DateTime(2024, 1, 21, 12, 54, 58, 563, DateTimeKind.Utc).AddTicks(2743),
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2L,
                            CreatedAt = new DateTime(2023, 12, 20, 12, 54, 58, 563, DateTimeKind.Utc).AddTicks(2753),
                            Description = "A panel discussion on the future of technology.",
                            EndAt = new DateTime(2024, 2, 22, 13, 54, 58, 563, DateTimeKind.Utc).AddTicks(2752),
                            EventId = 2L,
                            Name = "Panel Discussion",
                            SpeakerId = "2",
                            StartAt = new DateTime(2024, 2, 22, 12, 54, 58, 563, DateTimeKind.Utc).AddTicks(2751),
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3L,
                            CreatedAt = new DateTime(2023, 12, 20, 12, 54, 58, 563, DateTimeKind.Utc).AddTicks(2755),
                            Description = "A discussion on the latest book club selection.",
                            EndAt = new DateTime(2024, 3, 23, 13, 54, 58, 563, DateTimeKind.Utc).AddTicks(2754),
                            EventId = 3L,
                            Name = "Book Club Discussion",
                            SpeakerId = "3",
                            StartAt = new DateTime(2024, 3, 23, 12, 54, 58, 563, DateTimeKind.Utc).AddTicks(2753),
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4L,
                            CreatedAt = new DateTime(2023, 12, 20, 12, 54, 58, 563, DateTimeKind.Utc).AddTicks(2758),
                            Description = "Hands-on workshop for aspiring artists.",
                            EndAt = new DateTime(2024, 4, 24, 14, 54, 58, 563, DateTimeKind.Utc).AddTicks(2757),
                            EventId = 4L,
                            Name = "Art Workshop",
                            SpeakerId = "4",
                            StartAt = new DateTime(2024, 4, 24, 12, 54, 58, 563, DateTimeKind.Utc).AddTicks(2756),
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5L,
                            CreatedAt = new DateTime(2023, 12, 20, 12, 54, 58, 563, DateTimeKind.Utc).AddTicks(2761),
                            Description = "Collaborative session to plan community initiatives.",
                            EndAt = new DateTime(2024, 5, 25, 13, 54, 58, 563, DateTimeKind.Utc).AddTicks(2760),
                            EventId = 5L,
                            Name = "Community Planning Session",
                            SpeakerId = "5",
                            StartAt = new DateTime(2024, 5, 25, 12, 54, 58, 563, DateTimeKind.Utc).AddTicks(2759),
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("MDC.Server.Domain.Entities.References.Language", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Languages");

                    b.HasData(
                        new
                        {
                            Id = (short)1,
                            CreatedAt = new DateTime(2023, 12, 20, 12, 54, 58, 563, DateTimeKind.Utc).AddTicks(2553),
                            Name = "English",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = (short)2,
                            CreatedAt = new DateTime(2023, 12, 20, 12, 54, 58, 563, DateTimeKind.Utc).AddTicks(2554),
                            Name = "Uzbek",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = (short)3,
                            CreatedAt = new DateTime(2023, 12, 20, 12, 54, 58, 563, DateTimeKind.Utc).AddTicks(2555),
                            Name = "French",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = (short)4,
                            CreatedAt = new DateTime(2023, 12, 20, 12, 54, 58, 563, DateTimeKind.Utc).AddTicks(2556),
                            Name = "German",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = (short)5,
                            CreatedAt = new DateTime(2023, 12, 20, 12, 54, 58, 563, DateTimeKind.Utc).AddTicks(2577),
                            Name = "Russian",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("MDC.Server.Domain.Entities.References.Location", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Latitude")
                        .HasColumnType("bigint");

                    b.Property<long>("Longitude")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Address = "123 Main St",
                            CreatedAt = new DateTime(2023, 12, 20, 12, 54, 58, 563, DateTimeKind.Utc).AddTicks(2606),
                            Latitude = 789012L,
                            Longitude = 123456L,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2L,
                            Address = "456 Oak Ave",
                            CreatedAt = new DateTime(2023, 12, 20, 12, 54, 58, 563, DateTimeKind.Utc).AddTicks(2607),
                            Latitude = 210987L,
                            Longitude = 654321L,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3L,
                            Address = "789 Elm St",
                            CreatedAt = new DateTime(2023, 12, 20, 12, 54, 58, 563, DateTimeKind.Utc).AddTicks(2608),
                            Latitude = 333444L,
                            Longitude = 111222L,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4L,
                            Address = "987 Pine Ave",
                            CreatedAt = new DateTime(2023, 12, 20, 12, 54, 58, 563, DateTimeKind.Utc).AddTicks(2609),
                            Latitude = 777888L,
                            Longitude = 555666L,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5L,
                            Address = "654 Birch Ln",
                            CreatedAt = new DateTime(2023, 12, 20, 12, 54, 58, 563, DateTimeKind.Utc).AddTicks(2611),
                            Latitude = 123789L,
                            Longitude = 999000L,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("MDC.Server.Domain.Entities.References.Region", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Regions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "City1",
                            Country = "Country1",
                            CreatedAt = new DateTime(2023, 12, 20, 12, 54, 58, 563, DateTimeKind.Utc).AddTicks(2408),
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            City = "City2",
                            Country = "Country2",
                            CreatedAt = new DateTime(2023, 12, 20, 12, 54, 58, 563, DateTimeKind.Utc).AddTicks(2410),
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            City = "City3",
                            Country = "Country3",
                            CreatedAt = new DateTime(2023, 12, 20, 12, 54, 58, 563, DateTimeKind.Utc).AddTicks(2412),
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            City = "City4",
                            Country = "Country4",
                            CreatedAt = new DateTime(2023, 12, 20, 12, 54, 58, 563, DateTimeKind.Utc).AddTicks(2413),
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            City = "City5",
                            Country = "Country5",
                            CreatedAt = new DateTime(2023, 12, 20, 12, 54, 58, 563, DateTimeKind.Utc).AddTicks(2413),
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("MDC.Server.Domain.Entities.Users.SpeakerDetail", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Company")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<short>("ExperienceYear")
                        .HasColumnType("smallint");

                    b.Property<string>("Position")
                        .HasColumnType("text");

                    b.Property<string>("SpeechImage")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("SpeakerDetails");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Company = "Tech Innovators",
                            CreatedAt = new DateTime(2023, 12, 20, 12, 54, 58, 563, DateTimeKind.Utc).AddTicks(3021),
                            ExperienceYear = (short)5,
                            Position = "Senior Software Engineer",
                            SpeechImage = "john_doe_speech_image.jpg",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = "1"
                        },
                        new
                        {
                            Id = 2L,
                            Company = "Health & Wellness Solutions",
                            CreatedAt = new DateTime(2023, 12, 20, 12, 54, 58, 563, DateTimeKind.Utc).AddTicks(3023),
                            ExperienceYear = (short)8,
                            Position = "Lead Nutritionist",
                            SpeechImage = "jane_smith_speech_image.jpg",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = "2"
                        },
                        new
                        {
                            Id = 3L,
                            Company = "Artistic Creations",
                            CreatedAt = new DateTime(2023, 12, 20, 12, 54, 58, 563, DateTimeKind.Utc).AddTicks(3024),
                            ExperienceYear = (short)10,
                            Position = "Chief Creative Officer",
                            SpeechImage = "michael_johnson_speech_image.jpg",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = "3"
                        },
                        new
                        {
                            Id = 4L,
                            Company = "GreenTech Solutions",
                            CreatedAt = new DateTime(2023, 12, 20, 12, 54, 58, 563, DateTimeKind.Utc).AddTicks(3025),
                            ExperienceYear = (short)7,
                            Position = "Environmental Scientist",
                            SpeechImage = "emily_anderson_speech_image.jpg",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = "4"
                        },
                        new
                        {
                            Id = 5L,
                            Company = "Innovative Designs",
                            CreatedAt = new DateTime(2023, 12, 20, 12, 54, 58, 563, DateTimeKind.Utc).AddTicks(3027),
                            ExperienceYear = (short)12,
                            Position = "Lead Architect",
                            SpeechImage = "william_taylor_speech_image.jpg",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = "5"
                        });
                });

            modelBuilder.Entity("MDC.Server.Domain.Entities.Users.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "21ac09da-439c-471d-b675-c85aa14e7c9c",
                            CreatedAt = new DateTime(2023, 12, 20, 12, 54, 58, 563, DateTimeKind.Utc).AddTicks(2927),
                            DateOfBirth = new DateTime(2023, 12, 20, 12, 54, 58, 563, DateTimeKind.Utc).AddTicks(2926),
                            Email = "john.doe@example.com",
                            EmailConfirmed = false,
                            FirstName = "John",
                            LastName = "Doe",
                            LockoutEnabled = false,
                            PhoneNumber = "123456789",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "b42b5e47-3640-41e0-a265-708fa38e2697",
                            TwoFactorEnabled = false
                        },
                        new
                        {
                            Id = "2",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "1cef9780-3448-4d14-b47e-082c69249088",
                            CreatedAt = new DateTime(2023, 12, 20, 12, 54, 58, 563, DateTimeKind.Utc).AddTicks(2932),
                            DateOfBirth = new DateTime(2023, 12, 20, 12, 54, 58, 563, DateTimeKind.Utc).AddTicks(2932),
                            Email = "jane.smith@example.com",
                            EmailConfirmed = false,
                            FirstName = "Jane",
                            LastName = "Smith",
                            LockoutEnabled = false,
                            PhoneNumber = "987654321",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "203e1d4c-d0e2-4e1e-bbf8-485aea03b77d",
                            TwoFactorEnabled = false
                        },
                        new
                        {
                            Id = "3",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "07ac8b55-a5b9-4d51-a0e0-4f88b55b8658",
                            CreatedAt = new DateTime(2023, 12, 20, 12, 54, 58, 563, DateTimeKind.Utc).AddTicks(2938),
                            DateOfBirth = new DateTime(2023, 12, 20, 12, 54, 58, 563, DateTimeKind.Utc).AddTicks(2938),
                            Email = "michael.johnson@example.com",
                            EmailConfirmed = false,
                            FirstName = "Michael",
                            LastName = "Johnson",
                            LockoutEnabled = false,
                            PhoneNumber = "555555555",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "5f56940c-f870-411a-9af6-a4bad3c2847f",
                            TwoFactorEnabled = false
                        },
                        new
                        {
                            Id = "4",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "eaca5e8b-5694-4ae0-834c-de9054dc496d",
                            CreatedAt = new DateTime(2023, 12, 20, 12, 54, 58, 563, DateTimeKind.Utc).AddTicks(2942),
                            DateOfBirth = new DateTime(2023, 12, 20, 12, 54, 58, 563, DateTimeKind.Utc).AddTicks(2942),
                            Email = "emily.anderson@example.com",
                            EmailConfirmed = false,
                            FirstName = "Emily",
                            LastName = "Anderson",
                            LockoutEnabled = false,
                            PhoneNumber = "333333333",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "1a9c81fd-8713-4a36-b9ab-90d3c9e0a183",
                            TwoFactorEnabled = false
                        },
                        new
                        {
                            Id = "5",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "35886f4e-72a9-482d-97b1-ecf1c47d3a61",
                            CreatedAt = new DateTime(2023, 12, 20, 12, 54, 58, 563, DateTimeKind.Utc).AddTicks(2946),
                            DateOfBirth = new DateTime(2023, 12, 20, 12, 54, 58, 563, DateTimeKind.Utc).AddTicks(2946),
                            Email = "william.taylor@example.com",
                            EmailConfirmed = false,
                            FirstName = "William",
                            LastName = "Taylor",
                            LockoutEnabled = false,
                            PhoneNumber = "777777777",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "b7ffacf8-84d8-42a0-a87a-877af4673f79",
                            TwoFactorEnabled = false
                        });
                });

            modelBuilder.Entity("MDC.Server.Domain.Entities.Users.UserDetail", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Image")
                        .HasColumnType("text");

                    b.Property<string>("Resume")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserDatails");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Image = "john-doe-image-url",
                            Resume = "John Doe's resume details",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = "1"
                        },
                        new
                        {
                            Id = 2L,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Image = "jane-smith-image-url",
                            Resume = "Jane Smith's resume details",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = "2"
                        },
                        new
                        {
                            Id = 3L,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Image = "michael-johnson-image-url",
                            Resume = "Michael Johnson's resume details",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = "3"
                        },
                        new
                        {
                            Id = 4L,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Image = "emily-anderson-image-url",
                            Resume = "Emily Anderson's resume details",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = "4"
                        },
                        new
                        {
                            Id = 5L,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Image = "william-taylor-image-url",
                            Resume = "William Taylor's resume details",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = "5"
                        });
                });

            modelBuilder.Entity("MDC.Server.Domain.Entities.Users.UserEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("EventId")
                        .HasColumnType("bigint");

                    b.Property<short>("RoleId")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("UserEvents");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedAt = new DateTime(2023, 12, 20, 12, 54, 58, 563, DateTimeKind.Utc).AddTicks(3180),
                            EventId = 1L,
                            RoleId = (short)1,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = "1"
                        },
                        new
                        {
                            Id = 2L,
                            CreatedAt = new DateTime(2023, 12, 20, 12, 54, 58, 563, DateTimeKind.Utc).AddTicks(3181),
                            EventId = 2L,
                            RoleId = (short)2,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = "2"
                        },
                        new
                        {
                            Id = 3L,
                            CreatedAt = new DateTime(2023, 12, 20, 12, 54, 58, 563, DateTimeKind.Utc).AddTicks(3182),
                            EventId = 3L,
                            RoleId = (short)1,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = "3"
                        },
                        new
                        {
                            Id = 4L,
                            CreatedAt = new DateTime(2023, 12, 20, 12, 54, 58, 563, DateTimeKind.Utc).AddTicks(3183),
                            EventId = 4L,
                            RoleId = (short)3,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = "4"
                        },
                        new
                        {
                            Id = 5L,
                            CreatedAt = new DateTime(2023, 12, 20, 12, 54, 58, 563, DateTimeKind.Utc).AddTicks(3184),
                            EventId = 5L,
                            RoleId = (short)2,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = "5"
                        });
                });

            modelBuilder.Entity("MDC.Server.Domain.Entities.Users.UserLanguage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<short>("LanguageId")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.HasIndex("UserId");

                    b.ToTable("UserLanguages");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedAt = new DateTime(2023, 12, 20, 12, 54, 58, 563, DateTimeKind.Utc).AddTicks(3207),
                            LanguageId = (short)1,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = "1"
                        },
                        new
                        {
                            Id = 2L,
                            CreatedAt = new DateTime(2023, 12, 20, 12, 54, 58, 563, DateTimeKind.Utc).AddTicks(3208),
                            LanguageId = (short)2,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = "2"
                        },
                        new
                        {
                            Id = 3L,
                            CreatedAt = new DateTime(2023, 12, 20, 12, 54, 58, 563, DateTimeKind.Utc).AddTicks(3209),
                            LanguageId = (short)3,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = "3"
                        },
                        new
                        {
                            Id = 4L,
                            CreatedAt = new DateTime(2023, 12, 20, 12, 54, 58, 563, DateTimeKind.Utc).AddTicks(3209),
                            LanguageId = (short)4,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = "4"
                        },
                        new
                        {
                            Id = 5L,
                            CreatedAt = new DateTime(2023, 12, 20, 12, 54, 58, 563, DateTimeKind.Utc).AddTicks(3210),
                            LanguageId = (short)5,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = "5"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("MDC.Server.Domain.Entities.Communities.Community", b =>
                {
                    b.HasOne("MDC.Server.Domain.Entities.Communities.Community", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("MDC.Server.Domain.Entities.Communities.UserCommunity", b =>
                {
                    b.HasOne("MDC.Server.Domain.Entities.Communities.Community", "Community")
                        .WithMany("UserCommunities")
                        .HasForeignKey("CommunityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MDC.Server.Domain.Entities.Communities.CommunityRole", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MDC.Server.Domain.Entities.Users.User", "User")
                        .WithMany("UserCommunities")
                        .HasForeignKey("UserId");

                    b.Navigation("Community");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MDC.Server.Domain.Entities.Events.Event", b =>
                {
                    b.HasOne("MDC.Server.Domain.Entities.References.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("MDC.Server.Domain.Entities.Events.EventAsset", b =>
                {
                    b.HasOne("MDC.Server.Domain.Entities.Events.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("MDC.Server.Domain.Entities.Events.EventSession", b =>
                {
                    b.HasOne("MDC.Server.Domain.Entities.Events.Event", "Event")
                        .WithMany("Sessions")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MDC.Server.Domain.Entities.Users.User", "Speaker")
                        .WithMany()
                        .HasForeignKey("SpeakerId");

                    b.Navigation("Event");

                    b.Navigation("Speaker");
                });

            modelBuilder.Entity("MDC.Server.Domain.Entities.Users.SpeakerDetail", b =>
                {
                    b.HasOne("MDC.Server.Domain.Entities.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MDC.Server.Domain.Entities.Users.UserDetail", b =>
                {
                    b.HasOne("MDC.Server.Domain.Entities.Users.User", "User")
                        .WithOne("UserDetail")
                        .HasForeignKey("MDC.Server.Domain.Entities.Users.UserDetail", "UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MDC.Server.Domain.Entities.Users.UserEvent", b =>
                {
                    b.HasOne("MDC.Server.Domain.Entities.Events.Event", "Event")
                        .WithMany("Users")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MDC.Server.Domain.Entities.Events.EventRole", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MDC.Server.Domain.Entities.Users.User", "User")
                        .WithMany("Events")
                        .HasForeignKey("UserId");

                    b.Navigation("Event");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MDC.Server.Domain.Entities.Users.UserLanguage", b =>
                {
                    b.HasOne("MDC.Server.Domain.Entities.References.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MDC.Server.Domain.Entities.Users.User", "User")
                        .WithMany("Languages")
                        .HasForeignKey("UserId");

                    b.Navigation("Language");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("MDC.Server.Domain.Entities.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("MDC.Server.Domain.Entities.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MDC.Server.Domain.Entities.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("MDC.Server.Domain.Entities.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MDC.Server.Domain.Entities.Communities.Community", b =>
                {
                    b.Navigation("UserCommunities");
                });

            modelBuilder.Entity("MDC.Server.Domain.Entities.Events.Event", b =>
                {
                    b.Navigation("Sessions");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("MDC.Server.Domain.Entities.Users.User", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("Languages");

                    b.Navigation("UserCommunities");

                    b.Navigation("UserDetail");
                });
#pragma warning restore 612, 618
        }
    }
}
